# Generated by Django 3.0.6 on 2020-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_review_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='uploads.cars'),
        ),
    ]
