# Generated by Django 3.0.6 on 2020-05-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='car',
            new_name='car_id',
        ),
    ]
